default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: databridge_customer_service_development
  port: <%= ENV["DB_PORT"] || (ENV["DB_HOST"] == "db" ? 5432 : 5433) %>

test:
  <<: *default
  database: databridge_customer_service_test
  port: <%= ENV["DB_PORT"] || (ENV["DB_HOST"] == "db" ? 5432 : 5433) %>

production:
  <<: *default
  database: databridge_customer_service_production
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>